In [1]:
## importing modules
import math
math.sqrt(16)

4.0

In [2]:
from math import sqrt,pi
print(sqrt(16))
print(pi)

4.0
3.141592653589793


In [3]:
from math import *

print(sqrt(16))
print(pi)

4.0
3.141592653589793


In [4]:
import numpy as np
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [2]:
from package.maths import addition

addition(2,3)

ModuleNotFoundError: No module named 'package'

In [2]:
from package import maths

print(maths.addition)

AttributeError: module 'package.maths' has no attribute 'addition'

In [4]:
import numpy as np

arr1=np.array([1,2,3])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [7]:
arr2=np.array([1,2,3,4,5])
print(arr2.reshape(1,5))
print(arr2.shape)

[[1 2 3 4 5]]
(5,)


In [9]:
## 2d array

arr3=np.array([[1,2,3,4,5],[6,7,8,9,4]])
print(arr3)
print(arr3.shape)


[[1 2 3 4 5]
 [6 7 8 9 4]]
(2, 5)


In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [12]:
## identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
## attribute of numpy array

arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print("array",arr)
print("shape",arr.shape)
print("dimensions",arr.ndim)
print("size(no of elements)",arr.size)
print("data type",arr.dtype)

array [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
shape (1, 3, 3)
dimensions 3
size(no of elements) 9
data type int64


In [18]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("addition",arr1+arr2)
print("Sub",arr1-arr2)
print("Mul",arr1*arr2)
print("div",arr2/arr1)

addition [11 22 33 44 55]
Sub [ -9 -18 -27 -36 -45]
Mul [ 10  40  90 160 250]
div [10. 10. 10. 10. 10.]


In [21]:
## universal function

arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [23]:
# array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr[0][0])

1


In [24]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [26]:
print(arr[1:2,1:3])

[[6 7]]


In [30]:
print(arr[:,1:4])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [34]:
data=np.array([1,2,3,4,5])
mean=np.mean(data)
print(mean)

std_dev=np.std(data)
print(std_dev)
median=np.median(data)
print(median)

varience=np.var(data)
print(varience)

# normalization

normalization=(data-mean)/std_dev
print(normalization)


3.0
1.4142135623730951
3.0
2.0
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
