In [1]:
## numpy installation
!pip install numpy

DEPRECATION: Loading egg at c:\users\samar\appdata\local\programs\python\python313\lib\site-packages\jetbot_tools-0.0.0-py3.13.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330


In [4]:
import numpy as np

## create array using numpy
## create a 1D array

arr1=np.array([1,2,3])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [7]:
arr2=np.array([1,2,3,5])
print(arr2.shape)

(4,)


In [9]:
arr2.reshape(1,4)

array([[1, 2, 3, 5]])

In [10]:
## 2d array

arr3=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [20]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [19]:
## identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
## attributes of numpy arraey
arr=np.array([[1,2,3,],[4,5,6,],[7,8,9]])

print("array",arr)
print("shape",arr.shape)
print("dimensions",arr.ndim)
print("size",arr.size)
print("data type",arr.dtype)

array [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape (3, 3)
dimensions 2
size 9
data type int64


In [28]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("addition",arr1+arr2)
print("sub",arr1-arr2)
print("div",arr1/arr2)
print("mul",arr1*arr2)


addition [11 22 33 44 55]
sub [ -9 -18 -27 -36 -45]
div [0.1 0.1 0.1 0.1 0.1]
mul [ 10  40  90 160 250]


In [34]:
## universal functions

arr=np.array([2,3,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))
print(np.cos(arr))
print(np.tan(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[-2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]


In [37]:
## array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[1][1])

6


In [41]:
print(arr[1:1:3])

[]
